# Check https://circleci.com/docs/2.0/ for more details
#
version: 2.1

defaults: &config_project_defaults
  working_directory: ~/repo

executors:
  python_default:
    docker:
      - image: circleci/python:3.7.4

jobs:
  # Single deploy step that sends stuff to server
  deploy_all:
    <<: *config_project_defaults
    executor: python_default
    steps:
      - checkout
      - run:
          name: Create ssh key file
          command: echo $CPP_WS_KEY | base64 -d > ~/cpp-ws-key.pem
      - run:
          name: Set ssh key file permissions
          working_directory: ~/
          command: chmod 400 cpp-ws-key.pem
      - run:
          name: Install g++
          command: |
            ssh -o StrictHostKeyChecking=no -i "~/cpp-ws-key.pem" ubuntu@$SSH_HOST 'sudo apt-get update && sudo apt-get -y install g++'
      - run:
          name: killall processes belonging to ubuntu - stop previous server, if any
          command: |
            ssh -o StrictHostKeyChecking=no -i "~/cpp-ws-key.pem" ubuntu@$SSH_HOST 'sudo killall -u ubuntu' || true
      - run:
          name: Delete all files
          command: |
            ssh -o StrictHostKeyChecking=no -i "~/cpp-ws-key.pem" ubuntu@$SSH_HOST 'rm -rf ./* && ls -aL'
      - run:
          name: Send Files to Server
          command: |
            scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "~/cpp-ws-key.pem" ~/repo/* ubuntu@$SSH_HOST:/home/ubuntu/ || true
#      - run:
#          name: Compile
#          command: |
#            ssh -o StrictHostKeyChecking=no -i "~/cpp-ws-key.pem" ubuntu@$SSH_HOST 'g++ -o webserver main.cpp'
      - run:
          name: Compile, start and exit
          command: |
            ssh -o StrictHostKeyChecking=no -i "~/cpp-ws-key.pem" ubuntu@$SSH_HOST 'g++ -o webserver main.cpp && sudo ./webserver > logs.out & exit' || true

workflows:
  version: 2
  master_flow:
    jobs:
      - deploy_all
